#ifndef TEFLON_PREPROCESSING_PLATFORM_PLATFORMCURRENT_H
#define TEFLON_PREPROCESSING_PLATFORM_PLATFORMCURRENT_H

#include <teflon/preprocessing/platform/platform_defines.h>

#if defined(_WIN32)
#define TEFLON_PLATFORM_CURRENT TEFLON_PLATFORM_WINDOWS
#define TEFLON_PLATFORM_CURRENTEX TEFLON_PLATFORM_WINDOWS32
#define TEFLON_PLATFORM_NAME win32
#elif defined(_WIN64)
#define TEFLON_PLATFORM_CURRENT TEFLON_PLATFORM_WINDOWS
#define TEFLON_PLATFORM_CURRENTEX TEFLON_PLATFORM_WINDOWS64
#define TEFLON_PLATFORM_NAME win64
#elif defined(__CYGWIN__) && !defined(_WIN32)
#define TEFLON_PLATFORM_CURRENT TEFLON_PLATFORM_WINDOWS
#define TEFLON_PLATFORM_CURRENTEX TEFLON_PLATFORM_WINDOWSCYG
#define TEFLON_PLATFORM_NAME cygwin
#elif defined(__ANDROID__)
#define TEFLON_PLATFORM_CURRENT TEFLON_PLATFORM_ANDROID
#define TEFLON_PLATFORM_CURRENTEX TEFLON_PLATFORM_CURRENT
#define TEFLON_PLATFORM_NAME android
#elif defined(__linux__)
#define TEFLON_PLATFORM_CURRENT TEFLON_PLATFORM_LINUX
#define TEFLON_PLATFORM_CURRENTEX TEFLON_PLATFORM_CURRENT
#define TEFLON_PLATFORM_NAME linux
#elif defined(__unix__) || !defined(__APPLE__) && defined(__MACH__)
#include <sys/param.h>
#if defined(BSD)
#define TEFLON_PLATFORM_CURRENT TEFLON_PLATFORM_BSD
#define TEFLON_PLATFORM_CURRENTEX TEFLON_PLATFORM_CURRENT
#define TEFLON_PLATFORM_NAME bsd
#endif
#elif defined(__hpux)
#define TEFLON_PLATFORM_CURRENT TEFLON_PLATFORM_HPUX
#define TEFLON_PLATFORM_CURRENTEX TEFLON_PLATFORM_CURRENT
#define TEFLON_PLATFORM_NAME hpux
#elif defined(_AIX)
#define TEFLON_PLATFORM_CURRENT TEFLON_PLATFORM_AIX
#define TEFLON_PLATFORM_CURRENTEX TEFLON_PLATFORM_CURRENT
#define TEFLON_PLATFORM_NAME aix
#elif defined(__APPLE__) && defined(__MACH__)
#include <TargetConditionals.h>
#if TARGET_IPHONE_SIMULATOR == 1
#define TEFLON_PLATFORM_CURRENT TEFLON_PLATFORM_IOS
#define TEFLON_PLATFORM_CURRENTEX TEFLON_PLATFORM_IOSS
#define TEFLON_PLATFORM_NAME iossim
#elif TARGET_OS_IPHONE == 1
#define TEFLON_PLATFORM_CURRENT TEFLON_PLATFORM_IOS
#define TEFLON_PLATFORM_CURRENTEX TEFLON_PLATFORM_IOSR
#define TEFLON_PLATFORM_NAME iosreal
#elif TARGET_OS_MAC == 1
#define TEFLON_PLATFORM_CURRENT TEFLON_PLATFORM_OSX
#define TEFLON_PLATFORM_CURRENTEX TEFLON_PLATFORM_CURRENT
#define TEFLON_PLATFORM_NAME osx
#endif
#elif defined(__sun) && defined(__SVR4)
#define TEFLON_PLATFORM_CURRENT TEFLON_PLATFORM_SOLARIS
#define TEFLON_PLATFORM_CURRENTEX TEFLON_PLATFORM_CURRENT
#define TEFLON_PLATFORM_NAME solaris
#else
#define TEFLON_PLATFORM_CURRENT TEFLON_PLATFORM_UNKNOWN
#define TEFLON_PLATFORM_CURRENTEX TEFLON_PLATFORM_CURRENT
#define TEFLON_PLATFORM_NAME unknown
#endif

#endif // TEFLON_PREPROCESSING_PLATFORM_PLATFORMCURRENT_H